import { useMemo, useState } from 'react'
import { NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import {
  Activity, AlertTriangle, Anchor, BarChart3, Bell, Boxes, Bot, BrainCircuit,
  ChevronDown, CircleHelp, Clock3, CloudRain, Container, Gauge, Globe2, Layers3,
  LayoutDashboard, MapPin, Menu, MessageSquare, MoreHorizontal, PackageCheck,
  PanelLeftClose, Search, Settings, Ship, Sparkles, Truck, Warehouse, X, Zap,
} from 'lucide-react'

type ContainerRow = { id: string; origin: string; destination: string; status: string; eta: string; progress: number; risk: string }
const containers: ContainerRow[] = [
  { id: 'MSCU-4829104', origin: 'Shanghai', destination: 'Los Angeles', status: 'In transit', eta: '12 Jun, 14:30', progress: 72, risk: 'Low' },
  { id: 'TGHU-9042811', origin: 'Rotterdam', destination: 'New York', status: 'Delayed', eta: '13 Jun, 09:15', progress: 48, risk: 'High' },
  { id: 'CMAU-7720138', origin: 'Singapore', destination: 'Long Beach', status: 'On time', eta: '15 Jun, 18:00', progress: 31, risk: 'Low' },
  { id: 'OOLU-1912048', origin: 'Busan', destination: 'Seattle', status: 'In transit', eta: '17 Jun, 11:40', progress: 84, risk: 'Medium' },
]

const nav = [
  { to: '/', label: 'Overview', icon: LayoutDashboard }, { to: '/containers', label: 'Containers', icon: Container },
  { to: '/analytics', label: 'Analytics', icon: BarChart3 }, { to: '/warehouse', label: 'Warehouse', icon: Warehouse },
  { to: '/digital-twin', label: 'Digital Twin', icon: BrainCircuit },
]

function App() {
  const [sidebarOpen, setSidebarOpen] = useState(true)
  const [assistantOpen, setAssistantOpen] = useState(false)
  const location = useLocation()
  const pageTitle = nav.find(item => item.to === location.pathname)?.label || 'Overview'
  return <div className="app-frame">
    <aside className={`sidebar ${sidebarOpen ? '' : 'collapsed'}`}>
      <div className="brand"><div className="brand-mark"><Boxes size={19} /></div>{sidebarOpen && <><strong>FLEET<span>X</span></strong><button className="icon-button sidebar-toggle" onClick={() => setSidebarOpen(false)}><PanelLeftClose size={17} /></button></>}</div>
      <div className="workspace">{sidebarOpen && <><span>WORKSPACE</span><button>Global Operations <ChevronDown size={14} /></button></>}</div>
      <nav className="side-nav">{nav.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} title={label}><Icon size={18} />{sidebarOpen && <span>{label}</span>}{label === 'Digital Twin' && sidebarOpen && <em>NEW</em>}</NavLink>)}</nav>
      {sidebarOpen && <div className="sidebar-bottom"><NavLink to="/settings"><Settings size={17} />Settings</NavLink><NavLink to="/help"><CircleHelp size={17} />Help center</NavLink><div className="user-card"><div className="avatar">SS</div><div><b>Sanjana Shetty</b><small>Administrator</small></div><MoreHorizontal size={17} /></div></div>}
    </aside>
    {!sidebarOpen && <button className="expand-sidebar icon-button" onClick={() => setSidebarOpen(true)}><Menu size={19} /></button>}
    <section className="main-area">
      <header className="topbar"><div className="breadcrumb"><span>Workspace</span><b>/</b><strong>{pageTitle}</strong></div><div className="top-actions"><div className="search"><Search size={16} /><input placeholder="Search containers, routes..." /></div><button className="icon-button notification"><Bell size={18} /><i /></button><div className="top-avatar">SS</div></div></header>
      <main className="content"><Routes><Route path="/" element={<Overview onAssistant={() => setAssistantOpen(true)} />} /><Route path="/containers" element={<Containers />} /><Route path="/analytics" element={<Analytics />} /><Route path="/warehouse" element={<WarehousePage />} /><Route path="/digital-twin" element={<Twin />} /><Route path="*" element={<Overview onAssistant={() => setAssistantOpen(true)} />} /></Routes></main>
    </section>
    {assistantOpen && <Assistant close={() => setAssistantOpen(false)} />}
  </div>
}

function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</div> }
function Overview({ onAssistant }: { onAssistant: () => void }) {
  const [mapMode, setMapMode] = useState('Live map')
  return <><PageHeader eyebrow="Monday, June 10, 2024" title="Good morning, Sanjana" description="Here's what's happening across your global fleet today." action={<button className="primary" onClick={onAssistant}><Sparkles size={16} />Ask FleetX AI</button>} />
    <div className="metrics"><Metric icon={Container} label="Active containers" value="1,284" change="12.8%" detail="vs. last month" tone="orange" /><Metric icon={Clock3} label="On-time delivery" value="94.2%" change="2.4%" detail="vs. last month" tone="green" /><Metric icon={AlertTriangle} label="At-risk shipments" value="23" change="8.1%" detail="vs. last month" tone="red" /><Metric icon={Gauge} label="Avg. transit time" value="18.4d" change="4.6%" detail="vs. last month" tone="blue" /></div>
    <div className="dashboard-grid"><section className="panel map-panel"><div className="panel-head"><div><h2>Global fleet overview</h2><p>Real-time location and status of your shipments</p></div><div className="segmented">{['Live map', 'Routes'].map(m => <button className={mapMode === m ? 'active' : ''} onClick={() => setMapMode(m)} key={m}>{m}</button>)}</div></div><div className="map"><div className="map-grid" /><div className="route route-one" /><div className="route route-two" /><div className="route route-three" /><Pin x="25%" y="35%" label="Shanghai" count="342" color="orange" /><Pin x="45%" y="61%" label="Singapore" count="187" color="blue" /><Pin x="73%" y="37%" label="Rotterdam" count="221" color="green" /><Pin x="82%" y="67%" label="New York" count="96" color="purple" /><div className="map-legend"><span><i className="dot orange" />In transit</span><span><i className="dot green" />On time</span><span><i className="dot red" />At risk</span></div><div className="map-label"><Globe2 size={14} /> {mapMode === 'Live map' ? 'Live tracking enabled' : 'Showing active routes'}</div></div></section><section className="panel ai-panel"><div className="ai-orb"><Bot size={25} /></div><div className="eyebrow">FLEETX INTELLIGENCE</div><h2>Your operations copilot</h2><p>Ask questions about your fleet, find shipments, or discover potential disruptions before they happen.</p><button className="outline" onClick={onAssistant}><MessageSquare size={16} />Start a conversation</button><div className="suggestions"><small>Try asking</small><button onClick={onAssistant}>Which containers are delayed?</button><button onClick={onAssistant}>Show routes at risk</button></div></section></div>
    <section className="panel table-panel"><div className="panel-head"><div><h2>Container activity</h2><p>Your most recent shipment updates</p></div><NavLink className="text-link" to="/containers">View all containers <span>→</span></NavLink></div><ContainerTable rows={containers} /></section></>
}
function Metric({ icon: Icon, label, value, change, detail, tone }: any) { return <div className="metric"><div className={`metric-icon ${tone}`}><Icon size={19} /></div><div className="metric-copy"><span>{label}</span><strong>{value}</strong><small className={tone === 'red' ? 'negative' : ''}><b>↗ {change}</b> {detail}</small></div></div> }
function Pin({ x, y, label, count, color }: any) { return <div className="pin-wrap" style={{ left: x, top: y }}><div className={`pin ${color}`}><MapPin size={15} /></div><div className="pin-card"><b>{count}</b><span>{label}</span></div></div> }
function ContainerTable({ rows }: { rows: ContainerRow[] }) { return <div className="table-wrap"><table><thead><tr><th>CONTAINER</th><th>ROUTE</th><th>STATUS</th><th>ETA</th><th>PROGRESS</th><th>RISK</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><div className="container-id"><span className="mini-box"><Container size={14} /></span><b>{row.id}</b></div></td><td><span className="route-cell">{row.origin} <span>→</span> {row.destination}</span></td><td><span className={`status ${row.status.toLowerCase().replace(' ', '-')}`}><i />{row.status}</span></td><td>{row.eta}</td><td><div className="progress"><i style={{ width: `${row.progress}%` }} /></div><small>{row.progress}%</small></td><td><span className={`risk ${row.risk.toLowerCase()}`}>{row.risk}</span></td></tr>)}</tbody></table></div> }
function Containers() { const [filter, setFilter] = useState('All shipments'); const filtered = filter === 'All shipments' ? containers : containers.filter(r => r.status === filter); return <><PageHeader eyebrow="FLEET MONITORING" title="Containers" description="Track every shipment across your supply chain." action={<button className="primary"><Container size={16} />Add container</button>} /><div className="filter-bar"><div className="tabs">{['All shipments', 'In transit', 'Delayed', 'On time'].map(f => <button className={filter === f ? 'active' : ''} onClick={() => setFilter(f)} key={f}>{f}</button>)}</div><button className="filter"><Search size={15} /> Filter and sort</button></div><section className="panel table-panel full-table"><ContainerTable rows={filtered} /></section></> }
function Analytics() { return <><PageHeader eyebrow="PERFORMANCE INTELLIGENCE" title="Analytics" description="Understand your network performance with live operational data." action={<button className="outline"><BarChart3 size={16} />Export report</button>} /><div className="analytics-grid"><section className="panel chart-panel"><div className="panel-head"><div><h2>On-time delivery rate</h2><p>Last 30 days across all routes</p></div><strong className="chart-value">94.2%</strong></div><div className="chart"><div className="chart-lines" /><svg viewBox="0 0 700 220" preserveAspectRatio="none"><path d="M0 175 C70 150 75 170 130 130 S190 155 245 112 S315 138 365 95 S430 114 480 78 S550 112 600 60 S665 68 700 28" fill="none" stroke="#f05a28" strokeWidth="4" /><path d="M0 175 C70 150 75 170 130 130 S190 155 245 112 S315 138 365 95 S430 114 480 78 S550 112 600 60 S665 68 700 28 L700 220 L0 220Z" fill="url(#fill)" opacity=".16" /><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#f05a28" /><stop offset="1" stopColor="#fff" /></linearGradient></defs></svg></div><div className="chart-labels"><span>May 12</span><span>May 19</span><span>May 26</span><span>Jun 2</span><span>Jun 9</span></div></section><section className="panel breakdown"><h2>Network breakdown</h2><p>Shipment distribution by mode</p><Breakdown label="Ocean freight" value="68%" width="68%" color="orange" icon={Ship} /><Breakdown label="Road freight" value="21%" width="21%" color="blue" icon={Truck} /><Breakdown label="Air freight" value="11%" width="11%" color="purple" icon={CloudRain} /><div className="insight"><Zap size={16} /><span><b>AI insight:</b> Ocean delivery performance improved 6.4% this month.</span></div></section></div><div className="metrics mini-metrics"><Metric icon={Activity} label="Route efficiency" value="87.6%" change="6.2%" detail="improvement" tone="green" /><Metric icon={Anchor} label="Port dwell time" value="2.8d" change="12.4%" detail="reduction" tone="blue" /><Metric icon={PackageCheck} label="Claims rate" value="0.8%" change="0.2%" detail="improvement" tone="orange" /></div></> }
function Breakdown({ label, value, width, color, icon: Icon }: any) { return <div className="breakdown-row"><span className={`break-icon ${color}`}><Icon size={15} /></span><div><b>{label}</b><div className="progress"><i className={color} style={{ width }} /></div></div><strong>{value}</strong></div> }
function WarehousePage() { return <><PageHeader eyebrow="INVENTORY OPERATIONS" title="Warehouse control" description="Monitor inventory health and fulfillment across facilities." action={<button className="primary"><Warehouse size={16} />Manage inventory</button>} /><div className="warehouse-hero panel"><div><div className="eyebrow">LIVE CAPACITY</div><h2>North America distribution network</h2><p>4 facilities online · Last synced 2 minutes ago</p></div><div className="capacity"><div className="capacity-ring"><b>78%</b><small>utilized</small></div><div><b>Healthy capacity</b><span>22% available space</span></div></div></div><div className="warehouse-cards"><WarehouseCard name="Long Beach Hub" loc="Los Angeles, CA" value="84%" shipments="482 shipments" color="orange" /><WarehouseCard name="Port Newark" loc="Newark, NJ" value="71%" shipments="318 shipments" color="blue" /><WarehouseCard name="Rotterdam DC" loc="Rotterdam, NL" value="63%" shipments="264 shipments" color="green" /></div></> }
function WarehouseCard({ name, loc, value, shipments, color }: any) { return <div className="panel warehouse-card"><div className="warehouse-icon"><Warehouse size={22} /></div><h3>{name}</h3><span><MapPin size={13} />{loc}</span><div className="warehouse-stat"><strong>{value}</strong><small>capacity</small></div><div className="progress"><i className={color} style={{ width: value }} /></div><p>{shipments} <span>·</span> <b>Operational</b></p></div> }
function Twin() { const [running, setRunning] = useState(false); return <><PageHeader eyebrow="SCENARIO PLANNING" title="Digital twin simulation" description="Model disruptions and see how they impact your network in real time." action={<button className="primary" onClick={() => setRunning(!running)}><Zap size={16} />{running ? 'Pause simulation' : 'Run simulation'}</button>} /><div className="twin-grid"><section className="panel twin-canvas"><div className="twin-toolbar"><span><span className={`live-dot ${running ? 'pulsing' : ''}`} />{running ? 'Simulation running' : 'Simulation ready'}</span><button><Settings size={15} />Parameters</button></div><div className="network"><div className="network-line l1" /><div className="network-line l2" /><div className="network-line l3" /><div className="network-node n1"><Ship size={18} /><b>Shanghai</b><small>Origin port</small></div><div className="network-node n2"><Anchor size={18} /><b>Long Beach</b><small>Transshipment</small></div><div className="network-node n3"><Warehouse size={18} /><b>Chicago DC</b><small>Distribution</small></div><div className="network-node n4"><PackageCheck size={18} /><b>New York</b><small>Final mile</small></div></div></section><section className="panel scenario"><h2>Scenario controls</h2><p>Adjust variables to model a disruption</p><label>Scenario type<select><option>Port congestion</option><option>Weather disruption</option><option>Route closure</option></select></label><label>Congestion level<div className="range-label"><span>Moderate</span><b>42%</b></div><input type="range" defaultValue="42" /></label><div className="scenario-result"><div className="result-icon"><AlertTriangle size={17} /></div><div><small>Projected impact</small><strong>{running ? '+3.8 days average delay' : 'Run a simulation to see impact'}</strong></div></div><button className="outline full" onClick={() => setRunning(true)}><BrainCircuit size={16} />Analyze scenario</button></section></div></> }
function Assistant({ close }: { close: () => void }) { const [message, setMessage] = useState(''); return <div className="assistant"><div className="assistant-head"><div className="assistant-title"><div className="ai-orb small"><Bot size={18} /></div><div><b>FleetX AI</b><small>Operations copilot · Online</small></div></div><button className="icon-button" onClick={close}><X size={18} /></button></div><div className="assistant-body"><div className="bubble ai">Hello Sanjana! I’m your FleetX operations copilot. How can I help you today?</div><div className="bubble ai">I can help you track shipments, understand delays, and optimize your network.</div><div className="quick"><button>Show delayed containers</button><button>What needs attention?</button></div></div><div className="assistant-input"><input value={message} onChange={e => setMessage(e.target.value)} onKeyDown={e => e.key === 'Enter' && setMessage('')} placeholder="Ask anything about your fleet..." /><button onClick={() => setMessage('')}><Sparkles size={17} /></button></div></div> }
export default App
